### ISSUE TITLE
Verification Protocols rework - network cable

### ISSUE THREAD

**Issue by crexroth** [COSMIIC-Inc/Implantables-NetworkCable#4]
Hate to do this to you after the fact, but I finally got time to review Jenna's test reports and she had some typos and "errors" that I tracked back to this and it's an artifact of me working on the requirements at the same time (and I've just now realizing I uploaded the electrodes requirements doc to the wrong place) and not getting to look at your stuff sooner. I notice some of these things in the protocols for the electrodes as well.

Could you please change these things...
* Requirements addressed should reference that tag for the ID from the corresponding NNP-REQ document?
* The Revision History should be updated to have your name as author and date. Jenna put "First version of document" for summary of changes.
* Remove the approval history section from the end of document and table of contents.
You can choose if you want to port things over into the updated template I made last month (automatic bullet points and table of contents) or if you just want to work with what you already have. Whatever is faster.

Jenna just made these same changes for her Network Cable test reports.

**Comment by dr-mh** [comment]
All done:)
